# Generated by Django 5.2.12 on 2026-03-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_faceembedding_landmarks_detection_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='person_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
